export const SKILLS_LIST = [
    "JavaScript",
    "React",
    "Node.js",
    "HTML",
    "CSS",
    "Python",
    "Java",
    "C++",
    "C#",
    "TypeScript",
    "Angular",
    "Vue.js",
    "SQL",
    "MongoDB",
    "AWS",
    "Azure",
    "Docker",
    "Kubernetes",
    "Git",
    "RESTful APIs",
    "GraphQL",
    "Redux",
    "Tailwind CSS",
    "Next.js",
    "Express.js",
    "Firebase",
    "PostgreSQL",
    "MySQL",
    "NoSQL",
    "Data Structures",
    "Algorithms",
    "Machine Learning",
    "Deep Learning",
    "Data Analysis",
    "Data Visualization",
    "UI/UX Design",
    "Project Management",
    "Communication",
    "Problem Solving",
    "Teamwork",
    "Leadership",
    "Time Management",
    "Critical Thinking",
    "Creativity",
    "Adaptability",
    "Cloud Computing",
    "Cybersecurity",
    "DevOps",
    "Agile Methodology",
    "Scrum",
    "Kanban",
    "Testing",
    "Debugging",
    "Version Control",
    "Continuous Integration",
    "Continuous Deployment",
    "Microservices",
    "Serverless Architecture",
    "Blockchain",
    "Artificial Intelligence",
    "Internet of Things",
    "Big Data",
    "Data Mining",
    "Natural Language Processing",
    "Computer Vision",
    "Robotics",
    "Game Development",
    "Mobile Development",
    "Web Development",
    "Software Engineering",
    "Database Management",
    "Network Administration",
    "System Administration",
    "Technical Support",
    "Business Analysis",
    "Marketing",
    "Sales",
    "Finance",
    "Human Resources",
    "Operations",
    "Supply Chain Management",
    "Customer Service",
    "Product Management",
    "Strategy",
    "Consulting",
    "Research",
    "Education",
    "Training",
    "Writing",
    "Editing",
    "Translation",
    "Design",
    "Photography",
    "Video Production",
    "Music",
    "Art",
    "Sports",
    "Travel",
    "Cooking",
    "Gardening",
    "Reading",
    "Gaming",
    "Movies",
    "TV Shows",
    "Podcasts",
    "Social Media",
    "Blogging",
    "Vlogging",
    "Public Speaking",
    "Negotiation",
    "Presentation",
    "Mentoring",
    "Coaching",
    "Facilitation",
    "Networking",
    "Event Planning",
    "Fundraising",
    "Volunteering",
    "Community Organizing",
    "Activism",
    "Advocacy",
    "Policy Analysis",
    "Government Relations",
    "International Relations",
    "Diplomacy",
    "Law",
    "Medicine",
    "Engineering",
    "Science",
    "Mathematics",
    "Statistics",
    "Economics",
    "Psychology",
    "Sociology",
    "Anthropology",
    "History",
    "Philosophy",
    "Religion",
    "Literature",
    "Linguistics",
    "Geography",
    "Environmental Science",
    "Sustainability",
    "Renewable Energy",
    "Climate Change",
    "Conservation",
    "Agriculture",
    "Food Science",
    "Nutrition",
    "Health",
    "Wellness",
    "Fitness",
    "Sports Medicine",
    "Physical Therapy",
    "Occupational Therapy",
    "Speech Therapy",
    "Nursing",
    "Dentistry",
    "Pharmacy",
    "Optometry",
    "Veterinary Medicine",
    "Public Health",
    "Epidemiology",
    "Biostatistics",
    "Health Policy",
    "Health Administration",
    "Healthcare Management",
    "Medical Research",
    "Clinical Trials",
    "Drug Development",
    "Biotechnology",
    "Bioinformatics",
    "Genetics",
    "Genomics",
    "Proteomics",
    "Metabolomics",
    "Systems Biology",
    "Synthetic Biology",
    "Nanotechnology",
    "Materials Science",
    "Chemical Engineering",
    "Mechanical Engineering",
    "Electrical Engineering",
    "Computer Engineering",
    "Civil Engineering",
    "Aerospace Engineering",
    "Biomedical Engineering",
    "Environmental Engineering",
    "Industrial Engineering",
    "Manufacturing Engineering",
    "Software Testing",
    "Quality Assurance",
    "Data Science",
    "Business Intelligence",
    "Data Warehousing",
    "ETL",
    "Data Modeling",
    "Data Governance",
    "Data Security",
    "Cloud Security",
    "Network Security",
    "Application Security",
    "Endpoint Security",
    "Incident Response",
    "Vulnerability Management",
    "Penetration Testing",
    "Security Awareness Training",
    "Compliance",
    "Risk Management",
    "Auditing",
    "Governance",
    "Ethics",
    "Corporate Social Responsibility",
    "Sustainability Reporting",
    "Environmental Management Systems",
    "Social Impact Assessment",
    "Economic Development",
    "Poverty Reduction",
    "Education Reform",
    "Healthcare Access",
    "Affordable Housing",
    "Criminal Justice Reform",
    "Immigration Reform",
    "Climate Action",
    "Clean Energy Transition",
    "Sustainable Agriculture",
    "Water Conservation",
    "Waste Management",
    "Biodiversity Conservation",
    "Environmental Justice",
    "Social Justice",
    "Human Rights",
    "Gender Equality",
    "Racial Equity",
    "LGBTQ+ Rights",
    "Disability Rights",
    "Indigenous Rights",
    "Animal Welfare",
    "Global Health",
    "International Development",
    "Humanitarian Aid",
    "Disaster Relief",
    "Peacebuilding",
    "Conflict Resolution",
    "Democracy Promotion",
    "Good Governance",
    "Rule of Law",
    "Anti-Corruption",
    "Transparency",
    "Accountability",
    "Citizen Engagement",
    "Civic Education",
    "Media Literacy",
    "Critical Thinking Skills",
    "Problem-Solving Skills",
    "Communication Skills",
    "Collaboration Skills",
    "Creativity Skills",
    "Innovation Skills",
    "Leadership Skills",
    "Time Management Skills",
    "Stress Management Skills",
    "Emotional Intelligence",
    "Resilience",
    "Adaptability",
    "Growth Mindset",
    "Self-Awareness",
    "Self-Regulation",
    "Motivation",
    "Perseverance",
    "Grit",
    "Optimism",
    "Gratitude",
    "Mindfulness",
    "Compassion",
    "Empathy",
    "Altruism",
    "Service",
    "Purpose",
    "Meaning",
    "Happiness",
    "Well-being",
    "Flunency in English",
    "Flunency in Spanish",
    "Flunency in French",
    "Flunency in German",
    "Flunency in Chinese",
    "Flunency in Japanese",
    "Flunency in Korean",
    "Flunency in Arabic",
    "Flunency in Russian",
    "Flunency in Portuguese",
  ]
  
  export const UNIVERSITIES_LIST = [
    "Massachusetts Institute of Technology (MIT)",
    "Stanford University",
    "Harvard University",
    "California Institute of Technology (Caltech)",
    "University of Oxford",
    "ETH Zurich - Swiss Federal Institute of Technology",
    "University of Cambridge",
    "Imperial College London",
    "University of Chicago",
    "UCL (University College London)",
    "National University of Singapore (NUS)",
    "Peking University",
    "University of Pennsylvania",
    "Yale University",
    "Tsinghua University",
    "Princeton University",
    "Cornell University",
    "Columbia University",
    "The University of Hong Kong",
    "University of Michigan-Ann Arbor",
    "Johns Hopkins University",
    "University of Tokyo",
    "Kyoto University",
    "The Hong Kong University of Science and Technology",
    "Nanyang Technological University, Singapore (NTU)",
    "University of Toronto",
    "Northwestern University",
    "The University of Manchester",
    "Seoul National University",
    "McGill University",
    "Australian National University",
    "The University of Melbourne",
    "The University of Sydney",
    "New York University",
    "The University of New South Wales (UNSW Sydney)",
    "University of California, Berkeley (UCB)",
    "KAIST - Korea Advanced Institute of Science & Technology",
    "London School of Economics and Political Science (LSE)",
    "Duke University",
    "The University of Queensland",
    "City University of Hong Kong",
    "Carnegie Mellon University",
    "LMU Munich",
    "The Chinese University of Hong Kong (CUHK)",
    "Delft University of Technology",
    "Paris Sciences et Lettres – PSL Research University Paris",
    "École Polytechnique",
    "University of California, Los Angeles (UCLA)",
    "The University of Warwick",
    "Technical University of Munich",
    "University of Bristol",
    "King's College London",
    "Washington University in St. Louis",
    "The University of Edinburgh",
    "Heidelberg University",
    "Erasmus University Rotterdam",
    "University of Copenhagen",
    "KU Leuven",
    "Georgia Institute of Technology",
    "Lomonosov Moscow State University",
    "Monash University",
    "Purdue University",
    "Uppsala University",
    "University of Amsterdam",
    "University of Texas at Austin",
    "University of Science and Technology of China",
    "Rice University",
    "University of Illinois at Urbana-Champaign",
    "Sungkyunkwan University (SKKU)",
    "University of Zurich",
    "Humboldt-Universität zu Berlin",
    "University of British Columbia",
    "Osaka University",
    "Stockholm University",
    "University of Munich",
    "RWTH Aachen University",
    "University of North Carolina at Chapel Hill",
    "Case Western Reserve University",
    "University of Glasgow",
    "Trinity College Dublin",
    "Durham University",
    "University of Southern California",
    "University of Geneva",
    "University of Bern",
    "University of Adelaide",
    "University of Helsinki",
    "University of Oslo",
    "University of Vienna",
    "Utrecht University",
    "Aalto University",
    "University of Alberta",
    "McMaster University",
    "University of Lausanne",
    "University of Sheffield",
    "University of Southampton",
    "University of Pittsburgh",
    "University of York",
    "Cardiff University",
    "Queen Mary University of London",
    "University of Leeds",
    "University of Nottingham",
    "Vanderbilt University",
    "London Business School",
    "IESE Business School",
    "INSEAD",
    "HEC Paris",
    "IMD Business School",
    "Saïd Business School",
    "Judge Business School",
    "Wharton School",
    "Chicago Booth",
    "Kellogg School of Management",
    "Sloan School of Management",
    "Harvard Business School",
    "Stanford Graduate School of Business",
    "Columbia Business School",
    "Haas School of Business",
    "Anderson School of Management",
    "Ross School of Business",
    "Darden School of Business",
    "Tuck School of Business",
    "Stern School of Business",
    "Yale School of Management",
    "Rotman School of Management",
    "Schulich School of Business",
    "Ivey Business School",
    "Desautels Faculty of Management",
    "Smith School of Business",
    "Sauder School of Business",
    "Alberta School of Business",
    "DeGroote School of Business",
    "Beedie School of Business",
    "Edwards School of Business",
    "Asper School of Business",
    "Sobey School of Business",
    "Telfer School of Management",
    "Ted Rogers School of Management",
    "Goodman School of Business",
    "Hill School of Business",
    "Edwards School of Business",
    "Asper School of Business",
    "Sobey School of Business",
    "Telfer School of Management",
    "Ted Rogers School of Management",
    "Goodman School of Business",
    "Hill School of Business",
  ]
  
  export const DEGREE_TYPES = [
    "Bachelor of Science (BSc)",
    "Bachelor of Arts (BA)",
    "Master of Science (MSc)",
    "Master of Arts (MA)",
    "Doctor of Philosophy (PhD)",
    "Associate of Arts (AA)",
    "Associate of Science (AS)",
    "Bachelor of Engineering (BEng)",
    "Master of Engineering (MEng)",
    "Bachelor of Business Administration (BBA)",
    "Master of Business Administration (MBA)",
    "Juris Doctor (JD)",
    "Master of Laws (LLM)",
    "Medical Doctor (MD)",
    "Doctor of Dental Surgery (DDS)",
    "Doctor of Pharmacy (PharmD)",
    "Bachelor of Architecture (BArch)",
    "Master of Architecture (MArch)",
    "Bachelor of Fine Arts (BFA)",
    "Master of Fine Arts (MFA)",
    "Bachelor of Education (BEd)",
    "Master of Education (MEd)",
    "Bachelor of Music (BMus)",
    "Master of Music (MMus)",
    "Bachelor of Technology (BTech)",
    "Master of Technology (MTech)",
    "Diploma",
    "Certificate",
  ]
  
  export const generateYearsList = () => {
    const currentYear = new Date().getFullYear()
    const startYear = 1970
    const years = []
    for (let i = currentYear; i >= startYear; i--) {
      years.push(String(i))
    }
    return years
  }
  
  export const JOB_TITLES = [
    "Software Engineer",
    "Data Scientist",
    "Project Manager",
    "Product Manager",
    "Business Analyst",
    "Marketing Manager",
    "Sales Manager",
    "Financial Analyst",
    "Human Resources Manager",
    "Operations Manager",
    "Consultant",
    "Teacher",
    "Professor",
    "Doctor",
    "Nurse",
    "Engineer",
    "Architect",
    "Lawyer",
    "Accountant",
    "Auditor",
    "Designer",
    "Developer",
    "Analyst",
    "Manager",
    "Director",
    "Vice President",
    "President",
    "CEO",
    "CTO",
    "CFO",
    "COO",
    "CIO",
    "CMO",
    "CCO",
    "CPO",
    "CSO",
    "CAO",
    "CBO",
    "CDO",
    "CHO",
    "CLO",
    "CMO",
    "CNO",
    "CPO",
    "CRO",
    "CSO",
    "CVO",
    "CWO",
    "CXO",
    "CYO",
    "CZO",
    "Database Administrator",
    "Network Administrator",
    "System Administrator",
    "Security Analyst",
    "Help Desk Technician",
    "Technical Support Specialist",
    "Web Developer",
    "Front-End Developer",
    "Back-End Developer",
    "Full-Stack Developer",
    "Mobile App Developer",
    "Game Developer",
    "UI Designer",
    "UX Designer",
    "Graphic Designer",
    "Web Designer",
    "Content Writer",
    "Copywriter",
    "Editor",
    "Proofreader",
    "Translator",
    "Social Media Manager",
    "Digital Marketing Specialist",
    "SEO Specialist",
    "SEM Specialist",
    "Email Marketing Specialist",
    "Content Marketing Specialist",
    "Public Relations Specialist",
    "Event Planner",
    "Fundraiser",
    "Volunteer Coordinator",
    "Community Organizer",
    "Activist",
    "Advocate",
    "Policy Analyst",
    "Government Relations Specialist",
    "International Relations Specialist",
    "Diplomat",
    "Judge",
    "Paralegal",
    "Legal Secretary",
    "Medical Assistant",
    "Dental Assistant",
    "Pharmacist",
    "Optometrist",
    "Veterinarian",
    "Public Health Specialist",
    "Epidemiologist",
    "Biostatistician",
    "Health Policy Analyst",
    "Healthcare Administrator",
    "Medical Researcher",
    "Clinical Trial Coordinator",
    "Drug Developer",
    "Biotechnologist",
    "Bioinformatician",
    "Geneticist",
    "Genomicist",
    "Proteomicist",
    "Metabolomicist",
    "Systems Biologist",
    "Synthetic Biologist",
    "Nanotechnologist",
    "Materials Scientist",
    "Chemical Engineer",
    "Mechanical Engineer",
    "Electrical Engineer",
    "Computer Engineer",
    "Civil Engineer",
    "Aerospace Engineer",
    "Biomedical Engineer",
    "Environmental Engineer",
    "Industrial Engineer",
    "Manufacturing Engineer",
    "Statistician",
    "Economist",
    "Psychologist",
    "Sociologist",
    "Anthropologist",
    "Historian",
    "Philosopher",
    "Religious Leader",
    "Librarian",
    "Archivist",
    "Curator",
    "Museum Director",
    "Artist",
    "Musician",
    "Actor",
    "Writer",
    "Poet",
    "Playwright",
    "Novelist",
    "Short Story Writer",
    "Screenwriter",
    "Journalist",
    "Blogger",
    "Vlogger",
    "Podcaster",
    "Public Speaker",
    "Negotiator",
    "Presenter",
    "Mentor",
    "Coach",
    "Facilitator",
    "Networker",
    "Event Coordinator",
    "Fundraising Manager",
    "Volunteer Recruiter",
    "Community Outreach Coordinator",
    "Political Campaign Manager",
    "Lobbyist",
    "Legislative Aide",
    "Policy Advisor",
    "International Affairs Specialist",
    "Foreign Service Officer",
    "Immigration Officer",
    "Customs Officer",
    "Border Patrol Agent",
    "Police Officer",
    "Detective",
    "Correctional Officer",
    "Probation Officer",
    "Social Worker",
    "Counselor",
    "Therapist",
    "Psychiatrist",
    "Psychologist",
    "Marriage and Family Therapist",
    "Substance Abuse Counselor",
    "School Counselor",
    "Career Counselor",
    "Rehabilitation Counselor",
    "Mental Health Counselor",
    "Guidance Counselor",
    "Vocational Counselor",
    "Pastoral Counselor",
    "Crisis Counselor",
    "Grief Counselor",
    "Trauma Counselor",
    "Addiction Counselor",
    "Family Counselor",
    "Child Counselor",
    "Adolescent Counselor",
    "Geriatric Counselor",
    "Group Counselor",
    "Individual Counselor",
    "Couples Counselor",
    "Relationship Counselor",
    "Divorce Counselor",
    "Premarital Counselor",
    "Sex Therapist",
    "Art Therapist",
    "Music Therapist",
    "Dance Therapist",
    "Drama Therapist",
    "Play Therapist",
    "Recreational Therapist",
    "Occupational Therapist",
    "Physical Therapist",
    "Speech Therapist",
    "Respiratory Therapist",
    "Radiation Therapist",
    "Massage Therapist",
    "Acupuncturist",
    "Chiropractor",
    "Naturopathic Doctor",
    "Homeopathic Doctor",
    "Herbalist",
    "Nutritionist",
    "Dietitian",
    "Personal Trainer",
    "Fitness Instructor",
    "Yoga Instructor",
    "Pilates Instructor",
    "Zumba Instructor",
    "Martial Arts Instructor",
    "Sports Coach",
    "Athletic Trainer",
    "Sports Psychologist",
    "Sports Agent",
    "Sports Broadcaster",
    "Sports Journalist",
    "Sports Photographer",
    "Sports Videographer",
    "Sports Analyst",
    "Sports Commentator",
    "Sports Statistician",
    "Sports Official",
    "Sports Referee",
    "Sports Umpire",
    "Sports Judge",
    "Sports Scorer",
    "Sports Timekeeper",
    "Sports Announcer",
    "Sports Publicist",
    "Sports Marketer",
    "Sports Salesperson",
    "Sports Sponsorship Coordinator",
    "Sports Event Planner",
    "Sports Facility Manager",
    "Sports Equipment Manager",
    "Sports Team Manager",
    "Sports League Administrator",
    "Sports Association Executive",
    "Sports Federation President",
    "Sports Club Owner",
    "Sports Team Owner",
    "Sports Investor",
    "Sports Philanthropist",
    "Sports Fan",
    "Sports Enthusiast",
    "Sports Volunteer",
    "Sports Parent",
    "Sports Child",
    "Sports Sibling",
    "Sports Grandparent",
    "Sports Friend",
    "Sports Rival",
    "Sports Hero",
    "Sports Legend",
    "Sports Icon",
    "Sports Role Model",
    "Sports Inspiration",
    "Sports Dreamer",
    "Sports Achiever",
    "Sports Winner",
    "Sports Loser",
    "Sports Competitor",
    "Sports Player",
    "Sports Athlete",
    "Sports Professional",
    "Sports Amateur",
    "Sports Olympian",
    "Sports Paralympian",
    "Sports Special Olympian",
    "Sports World Champion",
    "Sports National Champion",
    "Sports State Champion",
    "Sports Local Champion",
    "Sports School Champion",
    "Sports Team Captain",
    "Sports Team Member",
    "Sports Team Supporter",
    "Sports Team Sponsor",
    "Sports Team Booster",
    "Sports Team Fan Club President",
    "Sports Team Mascot",
    "Sports Team Cheerleader",
    "Sports Team Band Member",
    "Sports Team Photographer",
    "Sports Team Videographer",
    "Sports Team Journalist",
    "Sports Team Blogger",
    "Sports Team Vlogger",
    "Sports Team Podcaster",
    "Sports Team Social Media Manager",
    "Sports Team Digital Marketing Specialist",
    "Sports Team SEO Specialist",
    "Sports Team SEM Specialist",
    "Sports Team Email Marketing Specialist",
    "Sports Team Content Marketing Specialist",
    "Sports Team Public Relations Specialist",
    "Sports Team Event Planner",
    "Sports Team Fundraiser",
    "Sports Team Volunteer Coordinator",
    "Sports Team Community Organizer",
    "Sports Team Activist",
    "Sports Team Advocate",
    "Sports Team Policy Analyst",
    "Sports Team Government Relations Specialist",
    "Sports Team International Relations Specialist",
    "Sports Team Diplomat",
    "Sports Team Judge",
    "Sports Team Paralegal",
    "Sports Team Legal Secretary",
    "Sports Team Medical Assistant",
    "Sports Team Dental Assistant",
    "Sports Team Pharmacist",
    "Sports Team Optometrist",
    "Sports Team Veterinarian",
    "Sports Team Public Health Specialist",
    "Sports Team Epidemiologist",
    "Sports Team Biostatistician",
    "Sports Team Health Policy Analyst",
    "Sports Team Healthcare Administrator",
    "Sports Team Medical Researcher",
    "Sports Team Clinical Trial Coordinator",
    "Sports Team Drug Developer",
    "Sports Team Biotechnologist",
    "Sports Team Bioinformatician",
    "Sports Team Geneticist",
    "Sports Team Genomicist",
    "Sports Team Proteomicist",
    "Sports Team Metabolomicist",
    "Sports Team Systems Biologist",
    "Sports Team Synthetic Biologist",
    "Sports Team Nanotechnologist",
    "Sports Team Materials Scientist",
    "Sports Team Chemical Engineer",
    "Sports Team Mechanical Engineer",
    "Sports Team Electrical Engineer",
    "Sports Team Computer Engineer",
    "Sports Team Civil Engineer",
    "Sports Team Aerospace Engineer",
    "Sports Team Biomedical Engineer",
    "Sports Team Environmental Engineer",
    "Sports Team Industrial Engineer",
    "Sports Team Manufacturing Engineer",
    "Sports Team Statistician",
    "Sports Team Economist",
    "Sports Team Psychologist",
    "Sports Team Sociologist",
    "Sports Team Anthropologist",
    "Sports Team Historian",
    "Sports Team Philosopher",
    "Sports Team Religious Leader",
    "Sports Team Librarian",
    "Sports Team Archivist",
    "Sports Team Curator",
    "Sports Team Museum Director",
    "Sports Team Artist",
    "Sports Team Musician",
    "Sports Team Actor",
    "Sports Team Writer",
    "Sports Team Poet",
    "Sports Team Playwright",
    "Sports Team Novelist",
    "Sports Team Short Story Writer",
    "Sports Team Screenwriter",
    "Sports Team Journalist",
    "Sports Team Blogger",
    "Sports Team Vlogger",
    "Sports Team Podcaster",
    "Sports Team Public Speaker",
    "Sports Team Negotiator",
    "Sports Team Presenter",
    "Sports Team Mentor",
    "Sports Team Coach",
    "Sports Team Facilitator",
    "Sports Team Networker",
    "Sports Team Event Coordinator",
    "Sports Team Fundraising Manager",
    "Sports Team Volunteer Recruiter",
    "Sports Team Community Outreach Coordinator",
    "Sports Team Political Campaign Manager",
    "Sports Team Lobbyist",
    "Sports Team Legislative Aide",
    "Sports Team Policy Advisor",
    "Sports Team International Affairs Specialist",
    "Sports Team Foreign Service Officer",
    "Sports Team Immigration Officer",
    "Sports Team Customs Officer",
    "Sports Team Border Patrol Agent",
    "Sports Team Police Officer",
    "Sports Team Detective",
    "Sports Team Correctional Officer",
    "Sports Team Probation Officer",
    "Sports Team Social Worker",
    "Sports Team Counselor",
    "Sports Team Therapist",
    "Sports Team Psychiatrist",
    "Sports Team Psychologist",
    "Sports Team Marriage and Family Therapist",
    "Sports Team Substance Abuse Counselor",
    "Sports Team School Counselor",
    "Sports Team Career Counselor",
    "Sports Team Rehabilitation Counselor",
    "Sports Team Mental Health Counselor",
    "Sports Team Guidance Counselor",
    "Sports Team Vocational Counselor",
    "Sports Team Pastoral Counselor",
    "Sports Team Crisis Counselor",
    "Sports Team Grief Counselor",
    "Sports Team Trauma Counselor",
    "Sports Team Addiction Counselor",
    "Sports Team Family Counselor",
    "Sports Team Child Counselor",
    "Sports Team Adolescent Counselor",
    "Sports Team Geriatric Counselor",
    "Sports Team Group Counselor",
    "Sports Team Individual Counselor",
    "Sports Team Couples Counselor",
    "Sports Team Relationship Counselor",
    "Sports Team Divorce Counselor",
    "Sports Team Premarital Counselor",
    "Sports Team Sex Therapist",
    "Sports Team Art Therapist",
    "Sports Team Music Therapist",
    "Sports Team Dance Therapist",
    "Sports Team Drama Therapist",
    "Sports Team Play Therapist",
    "Sports Team Recreational Therapist",
    "Sports Team Occupational Therapist",
    "Sports Team Physical Therapist",
    "Sports Team Speech Therapist",
    "Sports Team Respiratory Therapist",
    "Sports Team Radiation Therapist",
    "Sports Team Massage Therapist",
    "Sports Team Acupuncturist",
    "Sports Team Chiropractor",
    "Sports Team Naturopathic Doctor",
    "Sports Team Homeopathic Doctor",
    "Sports Team Herbalist",
    "Sports Team Nutritionist",
    "Sports Team Dietitian",
    "Sports Team Personal Trainer",
    "Sports Team Fitness Instructor",
    "Sports Team Yoga Instructor",
    "Sports Team Pilates Instructor",
    "Sports Team Zumba Instructor",
    "Sports Team Martial Arts Instructor",
    "Sports Team Sports Coach",
    "Sports Team Athletic Trainer",
    "Sports Team Sports Psychologist",
    "Sports Team Sports Agent",
    "Sports Team Sports Broadcaster",
    "Sports Team Sports Journalist",
    "Sports Team Sports Photographer",
    "Sports Team Sports Videographer",
    "Sports Team Sports Analyst",
    "Sports Team Sports Commentator",
    "Sports Team Sports Statistician",
    "Sports Team Sports Official",
    "Sports Team Sports Referee",
    "Sports Team Sports Umpire",
    "Sports Team Sports Judge",
    "Sports Team Sports Scorer",
    "Sports Team Sports Timekeeper",
    "Sports Team Sports Announcer",
    "Sports Team Sports Publicist",
    "Sports Team Sports Marketer",
    "Sports Team Sports Salesperson",
    "Sports Team Sports Sponsorship Coordinator",
    "Sports Team Sports Event Planner",
    "Sports Team Sports Facility Manager",
    "Sports Team Sports Equipment Manager",
    "Sports Team Sports Team Manager",
    "Sports Team Sports League Administrator",
    "Sports Team Sports Association Executive",
    "Sports Team Sports Federation President",
    "Sports Team Sports Club Owner",
    "Sports Team Sports Team Owner",
    "Sports Team Sports Investor",
    "Sports Team Sports Philanthropist",
    "Sports Team Sports Fan",
    "Sports Team Sports Enthusiast",
    "Sports Team Sports Volunteer",
    "Sports Team Sports Parent",
    "Sports Team Sports Child",
    "Sports Team Sports Sibling",
    "Sports Team Sports Grandparent",
    "Sports Team Sports Friend",
    "Sports Team Sports Rival",
    "Sports Team Sports Hero",
    "Sports Team Sports Legend",
    "Sports Team Sports Icon",
    "Sports Team Sports Role Model",
    "Sports Team Sports Inspiration",
    "Sports Team Sports Dreamer",
    "Sports Team Sports Achiever",
    "Sports Team Sports Winner",
    "Sports Team Sports Loser",
    "Sports Team Sports Competitor",
    "Sports Team Sports Player",
    "Sports Team Sports Athlete",
    "Sports Team Sports Professional",
    "Sports Team Sports Amateur",
    "Sports Team Sports Olympian",
    "Sports Team Sports Paralympian",
    "Sports Team Sports Special Olympian",
    "Sports Team Sports World Champion",
    "Sports Team Sports National Champion",
    "Sports Team Sports State Champion",
    "Sports Team Sports Local Champion",
    "Sports Team Sports School Champion",
    "Sports Team Sports Team Captain",
    "Sports Team Sports Team Member",
    "Sports Team Sports Team Supporter",
    "Sports Team Sports Team Sponsor",
    "Sports Team Sports Team Booster",
    "Sports Team Sports Team Fan Club President",
    "Sports Team Sports Team Mascot",
    "Sports Team Sports Team Cheerleader",
    "Sports Team Sports Team Band Member",
    "Sports Team Sports Team Photographer",
    "Sports Team Sports Team Videographer",
    "Sports Team Sports Team Journalist",
    "Sports Team Sports Team Blogger",
    "Sports Team Sports Team Vlogger",
    "Sports Team Sports Team Podcaster",
    "Sports Team Sports Team Social Media Manager",
    "Sports Team Sports Team Digital Marketing Specialist",
    "Sports Team Sports Team SEO Specialist",
    "Sports Team Sports Team SEM Specialist",
    "Sports Team Sports Team Email Marketing Specialist",
    "Sports Team Sports Team Content Marketing Specialist",
    "Sports Team Sports Team Public Relations Specialist",
    "Sports Team Sports Team Event Planner",
    "Sports Team Sports Team Fundraiser",
    "Sports Team Sports Team Volunteer Coordinator",
    "Sports Team Sports Team Community Organizer",
    "Sports Team Sports Team Activist",
    "Sports Team Sports Team Advocate",
    "Sports Team Sports Team Policy Analyst",
    "Sports Team Sports Team Government Relations Specialist",
    "Sports Team Sports Team International Relations Specialist",
    "Sports Team Sports Team Diplomat",
    "Sports Team Sports Team Judge",
    "Sports Team Sports Team Paralegal",
    "Sports Team Sports Team Legal Secretary",
    "Sports Team Sports Team Medical Assistant",
    "Sports Team Sports Team Dental Assistant",
    "Sports Team Sports Team Pharmacist",
    "Sports Team Sports Team Optometrist",
    "Sports Team Sports Team Veterinarian",
    "Sports Team Sports Team Public Health Specialist",
    "Sports Team Sports Team Epidemiologist",
    "Sports Team Sports Team Biostatistician",
    "Sports Team Sports Team Health Policy Analyst",
    "Sports Team Sports Team Healthcare Administrator",
    "Sports Team Sports Team Medical Researcher",
    "Sports Team Sports Team Clinical Trial Coordinator",
    "Sports Team Sports Team Drug Developer",
    "Sports Team Sports Team Biotechnologist",
    "Sports Team Sports Team Bioinformatician",
    "Sports Team Sports Team Geneticist",
    "Sports Team Sports Team Genomicist",
    "Sports Team Sports Team Proteomicist",
    "Sports Team Sports Team Metabolomicist",
    "Sports Team Sports Team Systems Biologist",
    "Sports Team Sports Team Synthetic Biologist",
    "Sports Team Sports Team Nanotechnologist",
    "Sports Team Sports Team Materials Scientist",
    "Sports Team Sports Team Chemical Engineer",
    "Sports Team Sports Team Mechanical Engineer",
    "Sports Team Sports Team Electrical Engineer",
    "Sports Team Sports Team Computer Engineer",
    "Sports Team Sports Team Civil Engineer",
    "Sports Team Sports Team Aerospace Engineer",
    "Sports Team Sports Team Biomedical Engineer",
    "Sports Team Sports Team Environmental Engineer",
    "Sports Team Sports Team Industrial Engineer",
    "Sports Team Sports Team Manufacturing Engineer",
    "Sports Team Sports Team Statistician",
    "Sports Team Sports Team Economist",
    "Sports Team Sports Team Psychologist",
    "Sports Team Sports Team Sociologist",
    "Sports Team Sports Team Anthropologist",
    "Sports Team Sports Team Historian",
    "Sports Team Sports Team Philosopher",
    "Sports Team Sports Team Religious Leader",
    "Sports Team Sports Team Librarian",
    "Sports Team Sports Team Archivist",
    "Sports Team Sports Team Curator",
    "Sports Team Sports Team Museum Director",
    "Sports Team Sports Team Artist",
    "Sports Team Sports Team Musician",
    "Sports Team Sports Team Actor",
    "Sports Team Sports Team Writer",
    "Sports Team Sports Team Poet",
    "Sports Team Sports Team Playwright",
    "Sports Team Sports Team Novelist",
    "Sports Team Sports Team Short Story Writer",
    "Sports Team Sports Team Screenwriter",
    "Sports Team Sports Team Journalist",
    "Sports Team Sports Team Blogger",
    "Sports Team Sports Team Vlogger",
    "Sports Team Sports Team Podcaster",
    "Sports Team Sports Team Public Speaker",
    "Sports Team Sports Team Negotiator",
    "Sports Team Sports Team Presenter",
    "Sports Team Sports Team Mentor",
    "Sports Team Sports Team Coach",
    "Sports Team Sports Team Facilitator",
    "Sports Team Sports Team Networker",
    "Sports Team Sports Team Event Coordinator",
    "Sports Team Sports Team Fundraising Manager",
    "Sports Team Sports Team Volunteer Recruiter",
    "Sports Team Sports Team Community Organizer",
    "Sports Team Sports Team Activist",
    "Sports Team Sports Team Advocate",
    "Sports Team Sports Team Policy Analyst",
    "Sports Team Sports Team Government Relations Specialist",
    "Sports Team Sports Team International Relations Specialist",
    "Sports Team Sports Team Diplomat",
    "Sports Team Sports Team Judge",
    "Sports Team Sports Team Paralegal",
    "Sports Team Sports Team Legal Secretary",
    "Sports Team Sports Team Medical Assistant",
    "Sports Team Sports Team Dental Assistant",
    "Sports Team Sports Team Pharmacist",
    "Sports Team Sports Team Optometrist",
    "Sports Team Sports Team Veterinarian",
    "Sports Team Sports Team Public Health Specialist",
    "Sports Team Sports Team Epidemiologist",
    "Sports Team Sports Team Biostatistician",
    "Sports Team Sports Team Health Policy Analyst",
    "Sports Team Sports Team Healthcare Administrator",
    "Sports Team Sports Team Medical Researcher",
    "Sports Team Sports Team Clinical Trial Coordinator",
    "Sports Team Sports Team Drug Developer",
    "Sports Team Sports Team Biotechnologist",
    "Sports Team Sports Team Bioinformatician",
    "Sports Team Sports Team Geneticist",
    "Sports Team Sports Team Genomicist",
    "Sports Team Sports Team Proteomicist",
    "Sports Team Sports Team Metabolomicist",
    "Sports Team Sports Team Systems Biologist",
    "Sports Team Sports Team Synthetic Biologist",
    "Sports Team Sports Team Nanotechnologist",
    "Sports Team Sports Team Materials Scientist",
    "Sports Team Sports Team Chemical Engineer",
    "Sports Team Sports Team Mechanical Engineer",
    "Sports Team Sports Team Electrical Engineer",
    "Sports Team Sports Team Computer Engineer",
    "Sports Team Sports Team Civil Engineer",
    "Sports Team Sports Team Aerospace Engineer",
    "Sports Team Sports Team Biomedical Engineer",
    "Sports Team Sports Team Environmental Engineer",
    "Sports Team Sports Team Industrial Engineer",
    "Sports Team Sports Team Manufacturing Engineer",
    "Sports Team Sports Team Statistician",
    "Sports Team Sports Team Economist",
    "Sports Team Sports Team Psychologist",
    "Sports Team Sports Team Sociologist",
    "Sports Team Sports Team Anthropologist",
    "Sports Team Sports Team Historian",
    "Sports Team Sports Team Philosopher",
    "Sports Team Sports Team Religious Leader",
    "Sports Team Sports Team Librarian",
    "Sports Team Sports Team Archivist",
    "Sports Team Sports Team Curator",
    "Sports Team Sports Team Museum Director",
    "Sports Team Sports Team Artist",
    "Sports Team Sports Team Musician",
    "Sports Team Sports Team Actor",
    "Sports Team Sports Team Writer",
    "Sports Team Sports Team Poet",
    "Sports Team Sports Team Playwright",
    "Sports Team Sports Team Novelist",
    "Sports Team Sports Team Short Story Writer",
    "Sports Team Sports Team Screenwriter",
    "Sports Team Sports Team Journalist",
    "Sports Team Sports Team Blogger",
    "Sports Team Sports Team Vlogger",
    "Sports Team Sports Team Podcaster",
    "Sports Team Sports Team Public Speaker",
    "Sports Team Sports Team Negotiator",
    "Sports Team Sports Team Presenter",
    "Sports Team Sports Team Mentor",
    "Sports Team Sports Team Coach",
    "Sports Team Sports Team Facilitator",
    "Sports Team Sports Team Networker",
    "Sports Team Sports Team Event Coordinator",
    "Sports Team Sports Team Fundraising Manager",
    "Sports Team Sports Team Volunteer Recruiter",
    "Sports Team Sports Team Community Organizer",
  ]
  